# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 296e7aa8da3afc0aca625648a684a5ccf2a3c6b3d8fa644623aae107fe0e0ca84c2cc52c7e26d1addf44f1e592ed3301007f974cf47cab9f4b686d525c25fa00

test:
  secret_key_base: 3d0a1fa6fb873bf9e9ba82283abda6274306fec66420d0f232ff5e9a6761774fc19062fd5081a7c2ee5c9d4d4a4eeb0c8ed2d44a3c51ae58d27e58beaa0e7b4a

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
